### ISSUE TITLE
As a precursor to #143 add milestones table and associations

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#718]
Even before we add the graphic timeline (maybe the top desire in our survey responses), we should start organizing the longitudinal data as employed on abbreviated data by the NYTimes here: http://www.nytimes.com/interactive/2016/07/12/us/looking-for-accountability-in-police-involved-deaths-of-blacks.html?_r=0

Specifically we should:
- [x] create the milestones model (name:string, e.g. "placed on leave" "indicted" "convicted", etc.)
- [x] create the article_milestone associative table (article_id, milestone_id, date)
- [x] add to the article/edit form

It is a very simple addition, but even before we figure out the graphic timeline, we can create very informative infographics with the longitudinal data which gets to the core tenet of EBWiki that we need to be looking at these cases over time.

**Comment by campgurus** [comment]
This is what the timeline looks like now. I am looking for better alternatives, and might, in the interim, just include a basic list at the bottom of the main content section:

<img width="908" alt="screen shot 2016-07-19 at 6 40 19 pm" src="https://cloud.githubusercontent.com/assets/1260659/16969089/a41b59b2-4de0-11e6-80c9-96337ce0b0cc.png">

**Comment by campgurus** [comment]
This is what the current vertical timeline looks like:
<img width="394" alt="screen shot 2016-07-20 at 11 12 30 am" src="https://cloud.githubusercontent.com/assets/1260659/16991844/ff9bcf26-4e6a-11e6-993d-0c600d631306.png">

There is some nice animation as the user scrolls down.

**Comment by trystant** [comment]
While I think that we need to have discussions on the timeline, both our thoughts on this & technology have changed in almost two years. Unless there's an objection, I'm closing this for posterity.  We can open a new timeline issue (and have all the knowledge in one place) when the time comes.
